package alper.FutbolApp.utility.enums;


public enum ERenkler {
	KIRMIZI_SARI,
	SARI_LACIVERT,
	SIYAH_BEYAZ,
	BORDO_MAVI,
	CIFT_KIRMIZI,
	TURUNCU_LACIVERT,
	SERITLI_KIRMIZI,
	YESIL_BEYAZ,
	KIRMIZI_BEYAZ,
	YESIL_MAVI,
	SIYAH_KIRMIZI,
	KIRMIZI_SIYAH,
	YESIL_SIYAH;
}